/**
 * UI icon name map and IconName type. Extracted from icons.ts for smaller module size.
 */

export type IconName =
  | 'grip-vertical'
  | 'grip-horizontal'
  | 'x'
  | 'rotate-cw'
  | 'plus'
  | 'sparkles'
  | 'eye'
  | 'eye-off'
  | 'power'
  | 'chevron-down'
  | 'chevron-right'
  | 'chevron-left'
  | 'maximize-2'
  | 'minimize-2'
  | 'play'
  | 'pause'
  | 'mouse-pointer'
  | 'hand'
  | 'lasso'
  | 'menu'
  | 'zoom-in'
  | 'picture-in-picture'
  | 'layout-sidebar-right'
  | 'layout-sidebar-left-collapse'
  | 'layout-grid'
  | 'grid-pattern'
  | 'square-split-horizontal'
  | 'hash-straight'
  | 'transition-left'
  | 'square-x'
  | 'preset'
  | 'folder-open'
  | 'search'
  | 'arrows-maximize'
  | 'arrows-minimize'
  | 'copy'
  | 'photo'
  | 'image-square'
  | 'video'
  | 'brand-youtube'
  | 'help-circle'
  | 'keyboard'
  | 'circle-check'
  | 'circle-x'
  | 'music'
  | 'chart-column'
  | 'arrow-move-right'
  | 'matrix'
  | 'equal'
  | 'minus'
  | 'minus-circle'
  | 'wave-sine'
  | 'waveform'
  | 'lock-access'
  | 'lock-access-off'
  | 'plug'
  | 'multiply'
  | 'curly-loop'
  | 'repeat'
  | 'skip-back'
  | 'skip-forward'
  | 'swap'
  | 'arrows-in-line-vertical';

/** IconName → Phosphor icon name (kebab-case) */
export const iconNameMap: Record<IconName, string> = {
  'grip-vertical': 'dots-six-vertical',
  'grip-horizontal': 'dots-six',
  'x': 'x',
  'rotate-cw': 'arrow-clockwise',
  'plus': 'plus',
  'sparkles': 'sparkle',
  'eye': 'eye',
  'eye-off': 'eye-slash',
  'power': 'power',
  'chevron-down': 'caret-down',
  'chevron-right': 'caret-right',
  'chevron-left': 'caret-left',
  'maximize-2': 'arrows-out',
  'minimize-2': 'arrows-in',
  'play': 'play',
  'pause': 'pause',
  'mouse-pointer': 'cursor-click',
  'hand': 'hand-pointing',
  'lasso': 'selection',
  'menu': 'list',
  'zoom-in': 'magnifying-glass-plus',
  'picture-in-picture': 'picture-in-picture',
  'layout-sidebar-right': 'sidebar-simple',
  'layout-sidebar-left-collapse': 'sidebar-simple',
  'layout-grid': 'grid-four',
  'grid-pattern': 'checkerboard',
  'square-split-horizontal': 'square-split-horizontal',
  'hash-straight': 'hash-straight',
  'transition-left': 'arrow-left',
  'square-x': 'x-square',
  'preset': 'bookmark',
  'folder-open': 'folder-open',
  'multiply': 'asterisk',
  'search': 'magnifying-glass',
  'arrows-maximize': 'arrows-out',
  'arrows-minimize': 'arrows-in',
  'copy': 'copy',
  'photo': 'image',
  'image-square': 'image-square',
  'video': 'video',
  'brand-youtube': 'youtube-logo',
  'help-circle': 'question',
  'keyboard': 'keyboard',
  'circle-check': 'check-circle',
  'circle-x': 'x-circle',
  'music': 'music-notes',
  'chart-column': 'chart-bar',
  'arrow-move-right': 'arrow-right',
  'matrix': 'grid-four',
  'equal': 'equals',
  'minus': 'minus',
  'minus-circle': 'minus-circle',
  'wave-sine': 'wave-sine',
  'waveform': 'waveform',
  'lock-access': 'lock',
  'lock-access-off': 'lock-open',
  'plug': 'plug',
  'curly-loop': 'infinity',
  'repeat': 'repeat',
  'skip-back': 'skip-back',
  'skip-forward': 'skip-forward',
  'swap': 'swap',
  'arrows-in-line-vertical': 'arrows-in-line-vertical',
};
