/**
 * Phosphor Icons Data Loader
 * Loads Phosphor icon JSON data at build time (no async fetch).
 *
 * Output is generated by `scripts/build-phosphor-icons.ts` into:
 * - public/phosphor-nodes-regular.json
 * - public/phosphor-nodes-fill.json
 *
 * Format: Record<string, Array<["path", { d: string }]>>
 */

type PhosphorPathNode = ['path', { d: string }];
type PhosphorIconData = PhosphorPathNode[];
type PhosphorIconsMap = Record<string, PhosphorIconData>;

// Phosphor path-data JSON (regular = line, fill = filled)
import phosphorNodesRegularData from '../../public/phosphor-nodes-regular.json';
import phosphorNodesFillData from '../../public/phosphor-nodes-fill.json';

/**
 * Kept as async for API compatibility with entrypoints.
 * Data is bundled at build time, so this is a no-op.
 */
export async function loadPhosphorIconData(): Promise<void> {
  // No-op: data is bundled at build time
}

export function getPhosphorNodesOutline(): PhosphorIconsMap {
  return (phosphorNodesRegularData as unknown as PhosphorIconsMap) ?? {};
}

export function getPhosphorNodesFilled(): PhosphorIconsMap {
  return (phosphorNodesFillData as unknown as PhosphorIconsMap) ?? {};
}
